version: "2"
linters:
  enable:
    - goconst
    - gocyclo
    - gosec
    - misspell
    - prealloc
    - revive
    - unconvert
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G104
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
