version: "2"

linters:
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 30
    gosec:
      excludes:
        - G104
  enable:
    - goconst
    - gocyclo
    - gosec
    - misspell
    - prealloc
    - unconvert
  disable:
    - revive
  exclusions:
    paths:
      - "build/"

run:
  timeout: 5m
  build-tags:
    - linux
  skip-dirs:
    - build
    - build/ios
    - build/darwin
    - build/android
