version: "2"

run:
  skip-dirs:
    - build/ios
    - build/darwin
    - build/android
  skip-files:
    - ".*\\.syso$"

linters:
  enable:
    - goconst
    - gocyclo
    - gosec
    - misspell
    - prealloc
    - revive
    - unconvert
  settings:
    goconst:
      min-len: 3
      min-occurrences: 3
    gocyclo:
      min-complexity: 30
    gosec:
      excludes:
        - G104
    misspell:
      locale: US
    revive:
      rules:
        - name: exported
          disabled: true
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
      - build/ios
      - build/darwin
      - build/android
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
