linters-settings:
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 30
  gosec:
    excludes:
      - G104

run:
  timeout: 5m
  skip-dirs:
    - build

issues:
  exclude-rules:
    - path: "build/"
      linters:
        - gocyclo
        - gosec
        - unused

linters:
  enable:
    - goconst
    - gocyclo
    - gosec
    - misspell
    - prealloc
    - unconvert
  disable:
    - revive
