version: 2

linters-settings:
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 30
  gosec:
    excludes:
      - G104
  misspell:
    locale: US
  revive:
    rules:
      - name: exported
        disabled: true

run:
  timeout: 5m
  skip-dirs:
    - build

issues:
  exclude-files:
    - "build/.*"
  exclude-patterns:
    - "build/"
  exclude-rules:
    - path: "build"
      linters:
        - gocyclo
        - gosec
        - unused
    - linters:
        - revive
      text: "(exported|package-comments|unused-parameter|indent-error-flow|redefines-builtin-id|superfluous-else)"
    - linters:
        - gosec
      text: "(G301|G304)"

linters:
  enable:
    - goconst
    - gocyclo
    - gosec
    - misspell
    - prealloc
    - unconvert
  disable:
    - revive
