// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export {
    CalculationProgress,
    ChartData,
    ChartEntry,
    GlucoseStatus,
    PredictedPoint,
    PredictionResult,
    Settings,
    Treatment
} from "./models.js";

import * as $models from "./models.js";

/**
 * DiabetesParameters represents calculated diabetes management parameters
 * @typedef {$models.DiabetesParameters} DiabetesParameters
 */
