// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * ChartData represents data for the glucose chart
 */
export class ChartData {
    "entries": ChartEntry[];
    "targetLow": number;
    "targetHigh": number;
    "urgentLow": number;
    "urgentHigh": number;
    "timeRangeHours": number;

    /**
     * "mg/dL" or "mmol/L"
     */
    "unit": string;

    /** Creates a new ChartData instance. */
    constructor($$source: Partial<ChartData> = {}) {
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("targetLow" in $$source)) {
            this["targetLow"] = 0;
        }
        if (!("targetHigh" in $$source)) {
            this["targetHigh"] = 0;
        }
        if (!("urgentLow" in $$source)) {
            this["urgentLow"] = 0;
        }
        if (!("urgentHigh" in $$source)) {
            this["urgentHigh"] = 0;
        }
        if (!("timeRangeHours" in $$source)) {
            this["timeRangeHours"] = 0;
        }
        if (!("unit" in $$source)) {
            this["unit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChartData instance from a string or object.
     */
    static createFrom($$source: any = {}): ChartData {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        return new ChartData($$parsedSource as Partial<ChartData>);
    }
}

/**
 * ChartEntry represents a single point on the chart
 */
export class ChartEntry {
    /**
     * Unix timestamp in milliseconds
     */
    "time": number;

    /**
     * Value in selected unit
     */
    "value": number;

    /**
     * Original mg/dL value
     */
    "valueMg": number;

    /**
     * Status for coloring
     */
    "status": string;

    /** Creates a new ChartEntry instance. */
    constructor($$source: Partial<ChartEntry> = {}) {
        if (!("time" in $$source)) {
            this["time"] = 0;
        }
        if (!("value" in $$source)) {
            this["value"] = 0;
        }
        if (!("valueMg" in $$source)) {
            this["valueMg"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChartEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ChartEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChartEntry($$parsedSource as Partial<ChartEntry>);
    }
}

/**
 * GlucoseStatus represents the current glucose status for display
 */
export class GlucoseStatus {
    /**
     * mg/dL
     */
    "value": number;

    /**
     * mmol/L
     */
    "valueMmol": number;

    /**
     * Arrow character
     */
    "trend": string;

    /**
     * Direction string
     */
    "direction": string;

    /**
     * Reading time
     */
    "time": time$0.Time;

    /**
     * Change from previous reading
     */
    "delta": number;

    /**
     * "normal", "high", "low", "urgent_high", "urgent_low"
     */
    "status": string;

    /**
     * Minutes since last reading
     */
    "staleMinutes": number;

    /**
     * True if data is stale (>15 min)
     */
    "isStale": boolean;

    /** Creates a new GlucoseStatus instance. */
    constructor($$source: Partial<GlucoseStatus> = {}) {
        if (!("value" in $$source)) {
            this["value"] = 0;
        }
        if (!("valueMmol" in $$source)) {
            this["valueMmol"] = 0;
        }
        if (!("trend" in $$source)) {
            this["trend"] = "";
        }
        if (!("direction" in $$source)) {
            this["direction"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = null;
        }
        if (!("delta" in $$source)) {
            this["delta"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("staleMinutes" in $$source)) {
            this["staleMinutes"] = 0;
        }
        if (!("isStale" in $$source)) {
            this["isStale"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlucoseStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): GlucoseStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlucoseStatus($$parsedSource as Partial<GlucoseStatus>);
    }
}

/**
 * Settings contains all application settings
 */
export class Settings {
    /**
     * Connection settings
     */
    "nightscoutUrl": string;

    /**
     * Plain API secret (will be hashed)
     */
    "apiSecret": string;

    /**
     * Token-based auth
     */
    "apiToken": string;

    /**
     * Use token instead of secret
     */
    "useToken": boolean;

    /**
     * Display settings
     * "mg/dL" or "mmol/L"
     */
    "unit": string;

    /**
     * Seconds (30-600)
     */
    "refreshInterval": number;

    /**
     * Glucose thresholds (in mg/dL, converted for display)
     */
    "targetLow": number;
    "targetHigh": number;
    "urgentLow": number;
    "urgentHigh": number;

    /**
     * Alert settings
     */
    "enableHighAlert": boolean;
    "enableLowAlert": boolean;
    "enableUrgentHighAlert": boolean;
    "enableUrgentLowAlert": boolean;
    "enableSoundAlerts": boolean;

    /**
     * 0 = no repeat
     */
    "repeatAlertMinutes": number;

    /**
     * Chart settings
     * Hours (default 4)
     */
    "chartTimeRange": number;

    /**
     * Days (default 7)
     */
    "chartMaxHistory": number;

    /**
     * "line", "points", "both"
     */
    "chartStyle": string;

    /**
     * Hex color
     */
    "chartColorInRange": string;
    "chartColorHigh": string;
    "chartColorLow": string;
    "chartColorUrgent": string;

    /**
     * Show target range band
     */
    "chartShowTarget": boolean;

    /**
     * Show current time marker
     */
    "chartShowNow": boolean;

    /**
     * System settings
     */
    "startMinimized": boolean;
    "autoStart": boolean;

    /**
     * Windows only
     */
    "showInTaskbar": boolean;

    /**
     * Window state (not user-configurable)
     */
    "windowWidth": number;
    "windowHeight": number;
    "windowX": number;
    "windowY": number;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("nightscoutUrl" in $$source)) {
            this["nightscoutUrl"] = "";
        }
        if (!("apiSecret" in $$source)) {
            this["apiSecret"] = "";
        }
        if (!("apiToken" in $$source)) {
            this["apiToken"] = "";
        }
        if (!("useToken" in $$source)) {
            this["useToken"] = false;
        }
        if (!("unit" in $$source)) {
            this["unit"] = "";
        }
        if (!("refreshInterval" in $$source)) {
            this["refreshInterval"] = 0;
        }
        if (!("targetLow" in $$source)) {
            this["targetLow"] = 0;
        }
        if (!("targetHigh" in $$source)) {
            this["targetHigh"] = 0;
        }
        if (!("urgentLow" in $$source)) {
            this["urgentLow"] = 0;
        }
        if (!("urgentHigh" in $$source)) {
            this["urgentHigh"] = 0;
        }
        if (!("enableHighAlert" in $$source)) {
            this["enableHighAlert"] = false;
        }
        if (!("enableLowAlert" in $$source)) {
            this["enableLowAlert"] = false;
        }
        if (!("enableUrgentHighAlert" in $$source)) {
            this["enableUrgentHighAlert"] = false;
        }
        if (!("enableUrgentLowAlert" in $$source)) {
            this["enableUrgentLowAlert"] = false;
        }
        if (!("enableSoundAlerts" in $$source)) {
            this["enableSoundAlerts"] = false;
        }
        if (!("repeatAlertMinutes" in $$source)) {
            this["repeatAlertMinutes"] = 0;
        }
        if (!("chartTimeRange" in $$source)) {
            this["chartTimeRange"] = 0;
        }
        if (!("chartMaxHistory" in $$source)) {
            this["chartMaxHistory"] = 0;
        }
        if (!("chartStyle" in $$source)) {
            this["chartStyle"] = "";
        }
        if (!("chartColorInRange" in $$source)) {
            this["chartColorInRange"] = "";
        }
        if (!("chartColorHigh" in $$source)) {
            this["chartColorHigh"] = "";
        }
        if (!("chartColorLow" in $$source)) {
            this["chartColorLow"] = "";
        }
        if (!("chartColorUrgent" in $$source)) {
            this["chartColorUrgent"] = "";
        }
        if (!("chartShowTarget" in $$source)) {
            this["chartShowTarget"] = false;
        }
        if (!("chartShowNow" in $$source)) {
            this["chartShowNow"] = false;
        }
        if (!("startMinimized" in $$source)) {
            this["startMinimized"] = false;
        }
        if (!("autoStart" in $$source)) {
            this["autoStart"] = false;
        }
        if (!("showInTaskbar" in $$source)) {
            this["showInTaskbar"] = false;
        }
        if (!("windowWidth" in $$source)) {
            this["windowWidth"] = 0;
        }
        if (!("windowHeight" in $$source)) {
            this["windowHeight"] = 0;
        }
        if (!("windowX" in $$source)) {
            this["windowX"] = 0;
        }
        if (!("windowY" in $$source)) {
            this["windowY"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

// Private type creation functions
const $$createType0 = ChartEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
