// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * CalculationProgress represents the progress of parameter calculation
 */
export class CalculationProgress {
    /**
     * Current stage name
     */
    "stage": string;

    /**
     * 0-100 percentage
     */
    "progress": number;
    "entriesProcessed": number;
    "totalEntries": number;
    "treatmentsProcessed": number;
    "totalTreatments": number;

    /**
     * seconds
     */
    "estimatedTimeRemaining": number;
    "startedAt": time$0.Time;
    "error"?: string;

    /** Creates a new CalculationProgress instance. */
    constructor($$source: Partial<CalculationProgress> = {}) {
        if (!("stage" in $$source)) {
            this["stage"] = "";
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("entriesProcessed" in $$source)) {
            this["entriesProcessed"] = 0;
        }
        if (!("totalEntries" in $$source)) {
            this["totalEntries"] = 0;
        }
        if (!("treatmentsProcessed" in $$source)) {
            this["treatmentsProcessed"] = 0;
        }
        if (!("totalTreatments" in $$source)) {
            this["totalTreatments"] = 0;
        }
        if (!("estimatedTimeRemaining" in $$source)) {
            this["estimatedTimeRemaining"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CalculationProgress instance from a string or object.
     */
    static createFrom($$source: any = {}): CalculationProgress {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CalculationProgress($$parsedSource as Partial<CalculationProgress>);
    }
}

/**
 * ChartData represents data for the glucose chart
 */
export class ChartData {
    "entries": ChartEntry[];
    "targetLow": number;
    "targetHigh": number;
    "urgentLow": number;
    "urgentHigh": number;
    "timeRangeHours": number;

    /**
     * "mg/dL" or "mmol/L"
     */
    "unit": string;

    /** Creates a new ChartData instance. */
    constructor($$source: Partial<ChartData> = {}) {
        if (!("entries" in $$source)) {
            this["entries"] = [];
        }
        if (!("targetLow" in $$source)) {
            this["targetLow"] = 0;
        }
        if (!("targetHigh" in $$source)) {
            this["targetHigh"] = 0;
        }
        if (!("urgentLow" in $$source)) {
            this["urgentLow"] = 0;
        }
        if (!("urgentHigh" in $$source)) {
            this["urgentHigh"] = 0;
        }
        if (!("timeRangeHours" in $$source)) {
            this["timeRangeHours"] = 0;
        }
        if (!("unit" in $$source)) {
            this["unit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChartData instance from a string or object.
     */
    static createFrom($$source: any = {}): ChartData {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        return new ChartData($$parsedSource as Partial<ChartData>);
    }
}

/**
 * ChartEntry represents a single point on the chart
 */
export class ChartEntry {
    /**
     * Unix timestamp in milliseconds
     */
    "time": number;

    /**
     * Value in selected unit
     */
    "value": number;

    /**
     * Original mg/dL value
     */
    "valueMg": number;

    /**
     * Status for coloring
     */
    "status": string;

    /** Creates a new ChartEntry instance. */
    constructor($$source: Partial<ChartEntry> = {}) {
        if (!("time" in $$source)) {
            this["time"] = 0;
        }
        if (!("value" in $$source)) {
            this["value"] = 0;
        }
        if (!("valueMg" in $$source)) {
            this["valueMg"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChartEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): ChartEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChartEntry($$parsedSource as Partial<ChartEntry>);
    }
}

/**
 * DiabetesParameters represents calculated diabetes management parameters
 */
export type DiabetesParameters = any;

/**
 * GlucoseStatus represents the current glucose status for display
 */
export class GlucoseStatus {
    /**
     * mg/dL
     */
    "value": number;

    /**
     * mmol/L
     */
    "valueMmol": number;

    /**
     * Arrow character
     */
    "trend": string;

    /**
     * Direction string
     */
    "direction": string;

    /**
     * Reading time
     */
    "time": time$0.Time;

    /**
     * Change from previous reading
     */
    "delta": number;

    /**
     * "normal", "high", "low", "urgent_high", "urgent_low"
     */
    "status": string;

    /**
     * Minutes since last reading
     */
    "staleMinutes": number;

    /**
     * True if data is stale (>15 min)
     */
    "isStale": boolean;

    /**
     * Insulin on Board (units)
     */
    "iob": number;

    /**
     * Carbs on Board (grams)
     */
    "cob": number;

    /** Creates a new GlucoseStatus instance. */
    constructor($$source: Partial<GlucoseStatus> = {}) {
        if (!("value" in $$source)) {
            this["value"] = 0;
        }
        if (!("valueMmol" in $$source)) {
            this["valueMmol"] = 0;
        }
        if (!("trend" in $$source)) {
            this["trend"] = "";
        }
        if (!("direction" in $$source)) {
            this["direction"] = "";
        }
        if (!("time" in $$source)) {
            this["time"] = null;
        }
        if (!("delta" in $$source)) {
            this["delta"] = 0;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("staleMinutes" in $$source)) {
            this["staleMinutes"] = 0;
        }
        if (!("isStale" in $$source)) {
            this["isStale"] = false;
        }
        if (!("iob" in $$source)) {
            this["iob"] = 0;
        }
        if (!("cob" in $$source)) {
            this["cob"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlucoseStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): GlucoseStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlucoseStatus($$parsedSource as Partial<GlucoseStatus>);
    }
}

/**
 * PredictedPoint represents a single predicted glucose value
 */
export class PredictedPoint {
    /**
     * Unix timestamp in milliseconds
     */
    "time": number;

    /**
     * Predicted glucose in mg/dL
     */
    "value": number;

    /**
     * Normalized integer for consistency
     */
    "valueMgDL": number;

    /**
     * Predicted glucose in mmol/L
     */
    "valueMmol": number;

    /**
     * Confidence level (0-100)
     */
    "confidence": number;

    /**
     * Factors contributing to this prediction
     * Expected glucose change from insulin
     */
    "insulinEffect": number;

    /**
     * Expected glucose change from carbs
     */
    "carbEffect": number;

    /**
     * Expected glucose change from current trend
     */
    "trendEffect": number;

    /** Creates a new PredictedPoint instance. */
    constructor($$source: Partial<PredictedPoint> = {}) {
        if (!("time" in $$source)) {
            this["time"] = 0;
        }
        if (!("value" in $$source)) {
            this["value"] = 0;
        }
        if (!("valueMgDL" in $$source)) {
            this["valueMgDL"] = 0;
        }
        if (!("valueMmol" in $$source)) {
            this["valueMmol"] = 0;
        }
        if (!("confidence" in $$source)) {
            this["confidence"] = 0;
        }
        if (!("insulinEffect" in $$source)) {
            this["insulinEffect"] = 0;
        }
        if (!("carbEffect" in $$source)) {
            this["carbEffect"] = 0;
        }
        if (!("trendEffect" in $$source)) {
            this["trendEffect"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PredictedPoint instance from a string or object.
     */
    static createFrom($$source: any = {}): PredictedPoint {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PredictedPoint($$parsedSource as Partial<PredictedPoint>);
    }
}

/**
 * PredictionResult contains glucose predictions
 */
export class PredictionResult {
    /**
     * Short-term predictions (more accurate, 1-2 hours)
     */
    "shortTerm": PredictedPoint[];

    /**
     * Long-term predictions (less accurate, 3-6 hours)
     */
    "longTerm": PredictedPoint[];

    /**
     * For LSTM model compatibility - flat list of predictions
     */
    "points"?: PredictedPoint[];

    /**
     * Unit for display (mg/dL or mmol/L)
     */
    "unit"?: string;

    /**
     * Active insulin on board
     */
    "iob": number;

    /**
     * Active carbs on board
     */
    "cob": number;

    /**
     * Predicted time until IOB is depleted
     * minutes
     */
    "iobDuration": number;

    /**
     * Predicted time until COB is absorbed
     * minutes
     */
    "cobDuration": number;

    /**
     * Time until predicted high threshold crossing (0 if not predicted or already high)
     */
    "highInMinutes": number;

    /**
     * Time until predicted low threshold crossing (0 if not predicted or already low)
     */
    "lowInMinutes": number;

    /**
     * Target thresholds used for high/low prediction
     * mg/dL
     */
    "highThreshold": number;

    /**
     * mg/dL
     */
    "lowThreshold": number;

    /**
     * Prediction metadata
     */
    "predictedAt": time$0.Time;

    /**
     * Current glucose value used
     */
    "basedOnGlucose": number;

    /**
     * Current trend (mg/dL per 5 min)
     */
    "basedOnTrend": number;

    /** Creates a new PredictionResult instance. */
    constructor($$source: Partial<PredictionResult> = {}) {
        if (!("shortTerm" in $$source)) {
            this["shortTerm"] = [];
        }
        if (!("longTerm" in $$source)) {
            this["longTerm"] = [];
        }
        if (!("iob" in $$source)) {
            this["iob"] = 0;
        }
        if (!("cob" in $$source)) {
            this["cob"] = 0;
        }
        if (!("iobDuration" in $$source)) {
            this["iobDuration"] = 0;
        }
        if (!("cobDuration" in $$source)) {
            this["cobDuration"] = 0;
        }
        if (!("highInMinutes" in $$source)) {
            this["highInMinutes"] = 0;
        }
        if (!("lowInMinutes" in $$source)) {
            this["lowInMinutes"] = 0;
        }
        if (!("highThreshold" in $$source)) {
            this["highThreshold"] = 0;
        }
        if (!("lowThreshold" in $$source)) {
            this["lowThreshold"] = 0;
        }
        if (!("predictedAt" in $$source)) {
            this["predictedAt"] = null;
        }
        if (!("basedOnGlucose" in $$source)) {
            this["basedOnGlucose"] = 0;
        }
        if (!("basedOnTrend" in $$source)) {
            this["basedOnTrend"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PredictionResult instance from a string or object.
     */
    static createFrom($$source: any = {}): PredictionResult {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("shortTerm" in $$parsedSource) {
            $$parsedSource["shortTerm"] = $$createField0_0($$parsedSource["shortTerm"]);
        }
        if ("longTerm" in $$parsedSource) {
            $$parsedSource["longTerm"] = $$createField1_0($$parsedSource["longTerm"]);
        }
        if ("points" in $$parsedSource) {
            $$parsedSource["points"] = $$createField2_0($$parsedSource["points"]);
        }
        return new PredictionResult($$parsedSource as Partial<PredictionResult>);
    }
}

/**
 * Settings contains all application settings
 */
export class Settings {
    /**
     * Connection settings
     */
    "nightscoutUrl": string;

    /**
     * Plain API secret (will be hashed)
     */
    "apiSecret": string;

    /**
     * Token-based auth
     */
    "apiToken": string;

    /**
     * Use token instead of secret
     */
    "useToken": boolean;

    /**
     * Display settings
     * "mg/dL" or "mmol/L"
     */
    "unit": string;

    /**
     * Seconds (30-600)
     */
    "refreshInterval": number;

    /**
     * Glucose thresholds (in mg/dL, converted for display)
     */
    "targetLow": number;
    "targetHigh": number;
    "urgentLow": number;
    "urgentHigh": number;

    /**
     * Alert settings
     */
    "enableHighAlert": boolean;
    "enableLowAlert": boolean;
    "enableUrgentHighAlert": boolean;
    "enableUrgentLowAlert": boolean;
    "enableSoundAlerts": boolean;

    /**
     * 0 = no repeat
     */
    "repeatAlertMinutes": number;

    /**
     * Chart settings
     * Hours (default 4)
     */
    "chartTimeRange": number;

    /**
     * Days (default 7)
     */
    "chartMaxHistory": number;

    /**
     * "line", "points", "both"
     */
    "chartStyle": string;

    /**
     * Hex color
     */
    "chartColorInRange": string;
    "chartColorHigh": string;
    "chartColorLow": string;
    "chartColorUrgent": string;

    /**
     * Show target range band
     */
    "chartShowTarget": boolean;

    /**
     * Show current time marker
     */
    "chartShowNow": boolean;

    /**
     * System settings
     */
    "startMinimized": boolean;
    "autoStart": boolean;

    /**
     * Windows only
     */
    "showInTaskbar": boolean;

    /**
     * Prediction settings
     * "statistical" or "ml"
     */
    "predictionMode": string;

    /**
     * Show KE Factor instead of/alongside ICR
     */
    "showKEFactor": boolean;

    /**
     * Window state (not user-configurable)
     */
    "windowWidth": number;
    "windowHeight": number;
    "windowX": number;
    "windowY": number;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("nightscoutUrl" in $$source)) {
            this["nightscoutUrl"] = "";
        }
        if (!("apiSecret" in $$source)) {
            this["apiSecret"] = "";
        }
        if (!("apiToken" in $$source)) {
            this["apiToken"] = "";
        }
        if (!("useToken" in $$source)) {
            this["useToken"] = false;
        }
        if (!("unit" in $$source)) {
            this["unit"] = "";
        }
        if (!("refreshInterval" in $$source)) {
            this["refreshInterval"] = 0;
        }
        if (!("targetLow" in $$source)) {
            this["targetLow"] = 0;
        }
        if (!("targetHigh" in $$source)) {
            this["targetHigh"] = 0;
        }
        if (!("urgentLow" in $$source)) {
            this["urgentLow"] = 0;
        }
        if (!("urgentHigh" in $$source)) {
            this["urgentHigh"] = 0;
        }
        if (!("enableHighAlert" in $$source)) {
            this["enableHighAlert"] = false;
        }
        if (!("enableLowAlert" in $$source)) {
            this["enableLowAlert"] = false;
        }
        if (!("enableUrgentHighAlert" in $$source)) {
            this["enableUrgentHighAlert"] = false;
        }
        if (!("enableUrgentLowAlert" in $$source)) {
            this["enableUrgentLowAlert"] = false;
        }
        if (!("enableSoundAlerts" in $$source)) {
            this["enableSoundAlerts"] = false;
        }
        if (!("repeatAlertMinutes" in $$source)) {
            this["repeatAlertMinutes"] = 0;
        }
        if (!("chartTimeRange" in $$source)) {
            this["chartTimeRange"] = 0;
        }
        if (!("chartMaxHistory" in $$source)) {
            this["chartMaxHistory"] = 0;
        }
        if (!("chartStyle" in $$source)) {
            this["chartStyle"] = "";
        }
        if (!("chartColorInRange" in $$source)) {
            this["chartColorInRange"] = "";
        }
        if (!("chartColorHigh" in $$source)) {
            this["chartColorHigh"] = "";
        }
        if (!("chartColorLow" in $$source)) {
            this["chartColorLow"] = "";
        }
        if (!("chartColorUrgent" in $$source)) {
            this["chartColorUrgent"] = "";
        }
        if (!("chartShowTarget" in $$source)) {
            this["chartShowTarget"] = false;
        }
        if (!("chartShowNow" in $$source)) {
            this["chartShowNow"] = false;
        }
        if (!("startMinimized" in $$source)) {
            this["startMinimized"] = false;
        }
        if (!("autoStart" in $$source)) {
            this["autoStart"] = false;
        }
        if (!("showInTaskbar" in $$source)) {
            this["showInTaskbar"] = false;
        }
        if (!("predictionMode" in $$source)) {
            this["predictionMode"] = "";
        }
        if (!("showKEFactor" in $$source)) {
            this["showKEFactor"] = false;
        }
        if (!("windowWidth" in $$source)) {
            this["windowWidth"] = 0;
        }
        if (!("windowHeight" in $$source)) {
            this["windowHeight"] = 0;
        }
        if (!("windowX" in $$source)) {
            this["windowX"] = 0;
        }
        if (!("windowY" in $$source)) {
            this["windowY"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

/**
 * Treatment represents a treatment entry from Nightscout (insulin, carbs, etc.)
 */
export class Treatment {
    "_id": string;
    "eventType": string;

    /**
     * Unix timestamp in milliseconds
     */
    "date": number;
    "dateString": string;
    "created_at": string;

    /**
     * Units of insulin
     */
    "insulin": number;

    /**
     * Grams of carbohydrates
     */
    "carbs": number;

    /**
     * Grams of protein
     */
    "protein": number;

    /**
     * Grams of fat
     */
    "fat": number;

    /**
     * Duration in minutes (for temp basals, etc.)
     */
    "duration": number;

    /**
     * Blood glucose value if recorded
     */
    "glucose": number;

    /**
     * "Sensor", "Finger", "Manual"
     */
    "glucoseType": string;

    /**
     * "mg/dl" or "mmol/l"
     */
    "units": string;
    "notes": string;
    "enteredBy": string;
    "device": string;

    /**
     * For basal changes
     * Basal change in percent
     */
    "percent": number;

    /**
     * Basal change in absolute value
     */
    "absolute": number;

    /**
     * For temp targets
     */
    "targetTop": number;
    "targetBottom": number;

    /**
     * For profile switches
     */
    "profile": string;
    "reason": string;

    /** Creates a new Treatment instance. */
    constructor($$source: Partial<Treatment> = {}) {
        if (!("_id" in $$source)) {
            this["_id"] = "";
        }
        if (!("eventType" in $$source)) {
            this["eventType"] = "";
        }
        if (!("date" in $$source)) {
            this["date"] = 0;
        }
        if (!("dateString" in $$source)) {
            this["dateString"] = "";
        }
        if (!("created_at" in $$source)) {
            this["created_at"] = "";
        }
        if (!("insulin" in $$source)) {
            this["insulin"] = 0;
        }
        if (!("carbs" in $$source)) {
            this["carbs"] = 0;
        }
        if (!("protein" in $$source)) {
            this["protein"] = 0;
        }
        if (!("fat" in $$source)) {
            this["fat"] = 0;
        }
        if (!("duration" in $$source)) {
            this["duration"] = 0;
        }
        if (!("glucose" in $$source)) {
            this["glucose"] = 0;
        }
        if (!("glucoseType" in $$source)) {
            this["glucoseType"] = "";
        }
        if (!("units" in $$source)) {
            this["units"] = "";
        }
        if (!("notes" in $$source)) {
            this["notes"] = "";
        }
        if (!("enteredBy" in $$source)) {
            this["enteredBy"] = "";
        }
        if (!("device" in $$source)) {
            this["device"] = "";
        }
        if (!("percent" in $$source)) {
            this["percent"] = 0;
        }
        if (!("absolute" in $$source)) {
            this["absolute"] = 0;
        }
        if (!("targetTop" in $$source)) {
            this["targetTop"] = 0;
        }
        if (!("targetBottom" in $$source)) {
            this["targetBottom"] = 0;
        }
        if (!("profile" in $$source)) {
            this["profile"] = "";
        }
        if (!("reason" in $$source)) {
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Treatment instance from a string or object.
     */
    static createFrom($$source: any = {}): Treatment {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Treatment($$parsedSource as Partial<Treatment>);
    }
}

// Private type creation functions
const $$createType0 = ChartEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = PredictedPoint.createFrom;
const $$createType3 = $Create.Array($$createType2);
