// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../../../time/models.js";

/**
 * CalculationProgress represents the progress of parameter calculation
 */
export class CalculationProgress {
    /**
     * Creates a new CalculationProgress instance.
     * @param {Partial<CalculationProgress>} [$$source = {}] - The source object to create the CalculationProgress.
     */
    constructor($$source = {}) {
        if (!("stage" in $$source)) {
            /**
             * Current stage name
             * @member
             * @type {string}
             */
            this["stage"] = "";
        }
        if (!("progress" in $$source)) {
            /**
             * 0-100 percentage
             * @member
             * @type {number}
             */
            this["progress"] = 0;
        }
        if (!("entriesProcessed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["entriesProcessed"] = 0;
        }
        if (!("totalEntries" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalEntries"] = 0;
        }
        if (!("treatmentsProcessed" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["treatmentsProcessed"] = 0;
        }
        if (!("totalTreatments" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["totalTreatments"] = 0;
        }
        if (!("estimatedTimeRemaining" in $$source)) {
            /**
             * seconds
             * @member
             * @type {number}
             */
            this["estimatedTimeRemaining"] = 0;
        }
        if (!("startedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["startedAt"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["error"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CalculationProgress instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CalculationProgress}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CalculationProgress(/** @type {Partial<CalculationProgress>} */($$parsedSource));
    }
}

/**
 * ChartData represents data for the glucose chart
 */
export class ChartData {
    /**
     * Creates a new ChartData instance.
     * @param {Partial<ChartData>} [$$source = {}] - The source object to create the ChartData.
     */
    constructor($$source = {}) {
        if (!("entries" in $$source)) {
            /**
             * @member
             * @type {ChartEntry[]}
             */
            this["entries"] = [];
        }
        if (!("targetLow" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["targetLow"] = 0;
        }
        if (!("targetHigh" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["targetHigh"] = 0;
        }
        if (!("urgentLow" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["urgentLow"] = 0;
        }
        if (!("urgentHigh" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["urgentHigh"] = 0;
        }
        if (!("timeRangeHours" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["timeRangeHours"] = 0;
        }
        if (!("unit" in $$source)) {
            /**
             * "mg/dL" or "mmol/L"
             * @member
             * @type {string}
             */
            this["unit"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChartData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChartData}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("entries" in $$parsedSource) {
            $$parsedSource["entries"] = $$createField0_0($$parsedSource["entries"]);
        }
        return new ChartData(/** @type {Partial<ChartData>} */($$parsedSource));
    }
}

/**
 * ChartEntry represents a single point on the chart
 */
export class ChartEntry {
    /**
     * Creates a new ChartEntry instance.
     * @param {Partial<ChartEntry>} [$$source = {}] - The source object to create the ChartEntry.
     */
    constructor($$source = {}) {
        if (!("time" in $$source)) {
            /**
             * Unix timestamp in milliseconds
             * @member
             * @type {number}
             */
            this["time"] = 0;
        }
        if (!("value" in $$source)) {
            /**
             * Value in selected unit
             * @member
             * @type {number}
             */
            this["value"] = 0;
        }
        if (!("valueMg" in $$source)) {
            /**
             * Original mg/dL value
             * @member
             * @type {number}
             */
            this["valueMg"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * Status for coloring
             * @member
             * @type {string}
             */
            this["status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ChartEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ChartEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ChartEntry(/** @type {Partial<ChartEntry>} */($$parsedSource));
    }
}

/**
 * DiabetesParameters represents calculated diabetes management parameters
 * @typedef {any} DiabetesParameters
 */

/**
 * GlucoseStatus represents the current glucose status for display
 */
export class GlucoseStatus {
    /**
     * Creates a new GlucoseStatus instance.
     * @param {Partial<GlucoseStatus>} [$$source = {}] - The source object to create the GlucoseStatus.
     */
    constructor($$source = {}) {
        if (!("value" in $$source)) {
            /**
             * mg/dL
             * @member
             * @type {number}
             */
            this["value"] = 0;
        }
        if (!("valueMmol" in $$source)) {
            /**
             * mmol/L
             * @member
             * @type {number}
             */
            this["valueMmol"] = 0;
        }
        if (!("trend" in $$source)) {
            /**
             * Arrow character
             * @member
             * @type {string}
             */
            this["trend"] = "";
        }
        if (!("direction" in $$source)) {
            /**
             * Direction string
             * @member
             * @type {string}
             */
            this["direction"] = "";
        }
        if (!("time" in $$source)) {
            /**
             * Reading time
             * @member
             * @type {time$0.Time}
             */
            this["time"] = null;
        }
        if (!("delta" in $$source)) {
            /**
             * Change from previous reading
             * @member
             * @type {number}
             */
            this["delta"] = 0;
        }
        if (!("status" in $$source)) {
            /**
             * "normal", "high", "low", "urgent_high", "urgent_low"
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("staleMinutes" in $$source)) {
            /**
             * Minutes since last reading
             * @member
             * @type {number}
             */
            this["staleMinutes"] = 0;
        }
        if (!("isStale" in $$source)) {
            /**
             * True if data is stale (>15 min)
             * @member
             * @type {boolean}
             */
            this["isStale"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new GlucoseStatus instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {GlucoseStatus}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new GlucoseStatus(/** @type {Partial<GlucoseStatus>} */($$parsedSource));
    }
}

/**
 * PredictedPoint represents a single predicted glucose value
 */
export class PredictedPoint {
    /**
     * Creates a new PredictedPoint instance.
     * @param {Partial<PredictedPoint>} [$$source = {}] - The source object to create the PredictedPoint.
     */
    constructor($$source = {}) {
        if (!("time" in $$source)) {
            /**
             * Unix timestamp in milliseconds
             * @member
             * @type {number}
             */
            this["time"] = 0;
        }
        if (!("value" in $$source)) {
            /**
             * Predicted glucose in mg/dL
             * @member
             * @type {number}
             */
            this["value"] = 0;
        }
        if (!("valueMmol" in $$source)) {
            /**
             * Predicted glucose in mmol/L
             * @member
             * @type {number}
             */
            this["valueMmol"] = 0;
        }
        if (!("confidence" in $$source)) {
            /**
             * Confidence level (0-100)
             * @member
             * @type {number}
             */
            this["confidence"] = 0;
        }
        if (!("insulinEffect" in $$source)) {
            /**
             * Factors contributing to this prediction
             * Expected glucose change from insulin
             * @member
             * @type {number}
             */
            this["insulinEffect"] = 0;
        }
        if (!("carbEffect" in $$source)) {
            /**
             * Expected glucose change from carbs
             * @member
             * @type {number}
             */
            this["carbEffect"] = 0;
        }
        if (!("trendEffect" in $$source)) {
            /**
             * Expected glucose change from current trend
             * @member
             * @type {number}
             */
            this["trendEffect"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PredictedPoint instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PredictedPoint}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PredictedPoint(/** @type {Partial<PredictedPoint>} */($$parsedSource));
    }
}

/**
 * PredictionResult contains glucose predictions
 */
export class PredictionResult {
    /**
     * Creates a new PredictionResult instance.
     * @param {Partial<PredictionResult>} [$$source = {}] - The source object to create the PredictionResult.
     */
    constructor($$source = {}) {
        if (!("shortTerm" in $$source)) {
            /**
             * Short-term predictions (more accurate, 1-2 hours)
             * @member
             * @type {PredictedPoint[]}
             */
            this["shortTerm"] = [];
        }
        if (!("longTerm" in $$source)) {
            /**
             * Long-term predictions (less accurate, 3-6 hours)
             * @member
             * @type {PredictedPoint[]}
             */
            this["longTerm"] = [];
        }
        if (!("iob" in $$source)) {
            /**
             * Active insulin on board
             * @member
             * @type {number}
             */
            this["iob"] = 0;
        }
        if (!("cob" in $$source)) {
            /**
             * Active carbs on board
             * @member
             * @type {number}
             */
            this["cob"] = 0;
        }
        if (!("iobDuration" in $$source)) {
            /**
             * Predicted time until IOB is depleted
             * minutes
             * @member
             * @type {number}
             */
            this["iobDuration"] = 0;
        }
        if (!("cobDuration" in $$source)) {
            /**
             * Predicted time until COB is absorbed
             * minutes
             * @member
             * @type {number}
             */
            this["cobDuration"] = 0;
        }
        if (!("predictedAt" in $$source)) {
            /**
             * Prediction metadata
             * @member
             * @type {time$0.Time}
             */
            this["predictedAt"] = null;
        }
        if (!("basedOnGlucose" in $$source)) {
            /**
             * Current glucose value used
             * @member
             * @type {number}
             */
            this["basedOnGlucose"] = 0;
        }
        if (!("basedOnTrend" in $$source)) {
            /**
             * Current trend (mg/dL per 5 min)
             * @member
             * @type {number}
             */
            this["basedOnTrend"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PredictionResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PredictionResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("shortTerm" in $$parsedSource) {
            $$parsedSource["shortTerm"] = $$createField0_0($$parsedSource["shortTerm"]);
        }
        if ("longTerm" in $$parsedSource) {
            $$parsedSource["longTerm"] = $$createField1_0($$parsedSource["longTerm"]);
        }
        return new PredictionResult(/** @type {Partial<PredictionResult>} */($$parsedSource));
    }
}

/**
 * Settings contains all application settings
 */
export class Settings {
    /**
     * Creates a new Settings instance.
     * @param {Partial<Settings>} [$$source = {}] - The source object to create the Settings.
     */
    constructor($$source = {}) {
        if (!("nightscoutUrl" in $$source)) {
            /**
             * Connection settings
             * @member
             * @type {string}
             */
            this["nightscoutUrl"] = "";
        }
        if (!("apiSecret" in $$source)) {
            /**
             * Plain API secret (will be hashed)
             * @member
             * @type {string}
             */
            this["apiSecret"] = "";
        }
        if (!("apiToken" in $$source)) {
            /**
             * Token-based auth
             * @member
             * @type {string}
             */
            this["apiToken"] = "";
        }
        if (!("useToken" in $$source)) {
            /**
             * Use token instead of secret
             * @member
             * @type {boolean}
             */
            this["useToken"] = false;
        }
        if (!("unit" in $$source)) {
            /**
             * Display settings
             * "mg/dL" or "mmol/L"
             * @member
             * @type {string}
             */
            this["unit"] = "";
        }
        if (!("refreshInterval" in $$source)) {
            /**
             * Seconds (30-600)
             * @member
             * @type {number}
             */
            this["refreshInterval"] = 0;
        }
        if (!("targetLow" in $$source)) {
            /**
             * Glucose thresholds (in mg/dL, converted for display)
             * @member
             * @type {number}
             */
            this["targetLow"] = 0;
        }
        if (!("targetHigh" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["targetHigh"] = 0;
        }
        if (!("urgentLow" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["urgentLow"] = 0;
        }
        if (!("urgentHigh" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["urgentHigh"] = 0;
        }
        if (!("enableHighAlert" in $$source)) {
            /**
             * Alert settings
             * @member
             * @type {boolean}
             */
            this["enableHighAlert"] = false;
        }
        if (!("enableLowAlert" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableLowAlert"] = false;
        }
        if (!("enableUrgentHighAlert" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableUrgentHighAlert"] = false;
        }
        if (!("enableUrgentLowAlert" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableUrgentLowAlert"] = false;
        }
        if (!("enableSoundAlerts" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enableSoundAlerts"] = false;
        }
        if (!("repeatAlertMinutes" in $$source)) {
            /**
             * 0 = no repeat
             * @member
             * @type {number}
             */
            this["repeatAlertMinutes"] = 0;
        }
        if (!("chartTimeRange" in $$source)) {
            /**
             * Chart settings
             * Hours (default 4)
             * @member
             * @type {number}
             */
            this["chartTimeRange"] = 0;
        }
        if (!("chartMaxHistory" in $$source)) {
            /**
             * Days (default 7)
             * @member
             * @type {number}
             */
            this["chartMaxHistory"] = 0;
        }
        if (!("chartStyle" in $$source)) {
            /**
             * "line", "points", "both"
             * @member
             * @type {string}
             */
            this["chartStyle"] = "";
        }
        if (!("chartColorInRange" in $$source)) {
            /**
             * Hex color
             * @member
             * @type {string}
             */
            this["chartColorInRange"] = "";
        }
        if (!("chartColorHigh" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chartColorHigh"] = "";
        }
        if (!("chartColorLow" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chartColorLow"] = "";
        }
        if (!("chartColorUrgent" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["chartColorUrgent"] = "";
        }
        if (!("chartShowTarget" in $$source)) {
            /**
             * Show target range band
             * @member
             * @type {boolean}
             */
            this["chartShowTarget"] = false;
        }
        if (!("chartShowNow" in $$source)) {
            /**
             * Show current time marker
             * @member
             * @type {boolean}
             */
            this["chartShowNow"] = false;
        }
        if (!("startMinimized" in $$source)) {
            /**
             * System settings
             * @member
             * @type {boolean}
             */
            this["startMinimized"] = false;
        }
        if (!("autoStart" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoStart"] = false;
        }
        if (!("showInTaskbar" in $$source)) {
            /**
             * Windows only
             * @member
             * @type {boolean}
             */
            this["showInTaskbar"] = false;
        }
        if (!("windowWidth" in $$source)) {
            /**
             * Window state (not user-configurable)
             * @member
             * @type {number}
             */
            this["windowWidth"] = 0;
        }
        if (!("windowHeight" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowHeight"] = 0;
        }
        if (!("windowX" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowX"] = 0;
        }
        if (!("windowY" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["windowY"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Settings}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Settings(/** @type {Partial<Settings>} */($$parsedSource));
    }
}

/**
 * Treatment represents a treatment entry from Nightscout (insulin, carbs, etc.)
 */
export class Treatment {
    /**
     * Creates a new Treatment instance.
     * @param {Partial<Treatment>} [$$source = {}] - The source object to create the Treatment.
     */
    constructor($$source = {}) {
        if (!("_id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["_id"] = "";
        }
        if (!("eventType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["eventType"] = "";
        }
        if (!("date" in $$source)) {
            /**
             * Unix timestamp in milliseconds
             * @member
             * @type {number}
             */
            this["date"] = 0;
        }
        if (!("dateString" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dateString"] = "";
        }
        if (!("created_at" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created_at"] = "";
        }
        if (!("insulin" in $$source)) {
            /**
             * Units of insulin
             * @member
             * @type {number}
             */
            this["insulin"] = 0;
        }
        if (!("carbs" in $$source)) {
            /**
             * Grams of carbohydrates
             * @member
             * @type {number}
             */
            this["carbs"] = 0;
        }
        if (!("protein" in $$source)) {
            /**
             * Grams of protein
             * @member
             * @type {number}
             */
            this["protein"] = 0;
        }
        if (!("fat" in $$source)) {
            /**
             * Grams of fat
             * @member
             * @type {number}
             */
            this["fat"] = 0;
        }
        if (!("duration" in $$source)) {
            /**
             * Duration in minutes (for temp basals, etc.)
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }
        if (!("glucose" in $$source)) {
            /**
             * Blood glucose value if recorded
             * @member
             * @type {number}
             */
            this["glucose"] = 0;
        }
        if (!("glucoseType" in $$source)) {
            /**
             * "Sensor", "Finger", "Manual"
             * @member
             * @type {string}
             */
            this["glucoseType"] = "";
        }
        if (!("units" in $$source)) {
            /**
             * "mg/dl" or "mmol/l"
             * @member
             * @type {string}
             */
            this["units"] = "";
        }
        if (!("notes" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["notes"] = "";
        }
        if (!("enteredBy" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["enteredBy"] = "";
        }
        if (!("device" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["device"] = "";
        }
        if (!("percent" in $$source)) {
            /**
             * For basal changes
             * Basal change in percent
             * @member
             * @type {number}
             */
            this["percent"] = 0;
        }
        if (!("absolute" in $$source)) {
            /**
             * Basal change in absolute value
             * @member
             * @type {number}
             */
            this["absolute"] = 0;
        }
        if (!("targetTop" in $$source)) {
            /**
             * For temp targets
             * @member
             * @type {number}
             */
            this["targetTop"] = 0;
        }
        if (!("targetBottom" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["targetBottom"] = 0;
        }
        if (!("profile" in $$source)) {
            /**
             * For profile switches
             * @member
             * @type {string}
             */
            this["profile"] = "";
        }
        if (!("reason" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["reason"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Treatment instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Treatment}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Treatment(/** @type {Partial<Treatment>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = ChartEntry.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = PredictedPoint.createFrom;
const $$createType3 = $Create.Array($$createType2);
