// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ForceRefresh() {
  return window['go']['app']['App']['ForceRefresh']();
}

export function GetAutoStartEnabled() {
  return window['go']['app']['App']['GetAutoStartEnabled']();
}

export function GetChartData(arg1, arg2) {
  return window['go']['app']['App']['GetChartData'](arg1, arg2);
}

export function GetCurrentStatus() {
  return window['go']['app']['App']['GetCurrentStatus']();
}

export function GetSettings() {
  return window['go']['app']['App']['GetSettings']();
}

export function GetVersion() {
  return window['go']['app']['App']['GetVersion']();
}

export function HideWindow() {
  return window['go']['app']['App']['HideWindow']();
}

export function IsConfigured() {
  return window['go']['app']['App']['IsConfigured']();
}

export function Quit() {
  return window['go']['app']['App']['Quit']();
}

export function SaveSettings(arg1) {
  return window['go']['app']['App']['SaveSettings'](arg1);
}

export function SendTestNotification() {
  return window['go']['app']['App']['SendTestNotification']();
}

export function ShowWindow() {
  return window['go']['app']['App']['ShowWindow']();
}

export function TestConnection(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['TestConnection'](arg1, arg2, arg3, arg4);
}
