// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ForceRefresh():Promise<void>;

export function GetAutoStartEnabled():Promise<boolean>;

export function GetChartData(arg1:number,arg2:number):Promise<models.ChartData>;

export function GetCurrentStatus():Promise<models.GlucoseStatus>;

export function GetSettings():Promise<models.Settings>;

export function GetVersion():Promise<string>;

export function HideWindow():Promise<void>;

export function IsConfigured():Promise<boolean>;

export function Quit():Promise<void>;

export function SaveSettings(arg1:models.Settings):Promise<void>;

export function SendTestNotification():Promise<void>;

export function ShowWindow():Promise<void>;

export function TestConnection(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<void>;
