// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * IOBCOBResult contains IOB and COB values
 */
export class IOBCOBResult {
    /**
     * Creates a new IOBCOBResult instance.
     * @param {Partial<IOBCOBResult>} [$$source = {}] - The source object to create the IOBCOBResult.
     */
    constructor($$source = {}) {
        if (!("iob" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["iob"] = 0;
        }
        if (!("cob" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["cob"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IOBCOBResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IOBCOBResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IOBCOBResult(/** @type {Partial<IOBCOBResult>} */($$parsedSource));
    }
}
