// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * IOBCOBResult contains IOB and COB values
 */
export class IOBCOBResult {
    "iob": number;
    "cob": number;

    /** Creates a new IOBCOBResult instance. */
    constructor($$source: Partial<IOBCOBResult> = {}) {
        if (!("iob" in $$source)) {
            this["iob"] = 0;
        }
        if (!("cob" in $$source)) {
            this["cob"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IOBCOBResult instance from a string or object.
     */
    static createFrom($$source: any = {}): IOBCOBResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IOBCOBResult($$parsedSource as Partial<IOBCOBResult>);
    }
}
