// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as prediction$0 from "../prediction/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelCalculation cancels an in-progress parameter calculation
 * @returns {$CancellablePromise<void>}
 */
export function CancelCalculation() {
    return $Call.ByID(2320468136);
}

/**
 * GetCalculationProgress returns the progress of the current parameter calculation
 * @returns {$CancellablePromise<models$0.CalculationProgress | null>}
 */
export function GetCalculationProgress() {
    return $Call.ByID(2929975047).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * @param {number} hours
 * @param {number} offsetHours
 * @returns {$CancellablePromise<models$0.ChartData | null>}
 */
export function GetChartData(hours, offsetHours) {
    return $Call.ByID(3917103465, hours, offsetHours).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * GetChartPredictionData returns prediction data formatted for the chart
 * @param {boolean} showLongTerm
 * @returns {$CancellablePromise<prediction$0.ChartPredictionData | null>}
 */
export function GetChartPredictionData(showLongTerm) {
    return $Call.ByID(3700879496, showLongTerm).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.GlucoseStatus | null>}
 */
export function GetCurrentStatus() {
    return $Call.ByID(704641666).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetIOBCOB returns current Insulin on Board and Carbs on Board
 * @returns {$CancellablePromise<$models.IOBCOBResult | null>}
 */
export function GetIOBCOB() {
    return $Call.ByID(37726841).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * GetPrediction returns glucose predictions based on current data
 * @returns {$CancellablePromise<models$0.PredictionResult | null>}
 */
export function GetPrediction() {
    return $Call.ByID(670056238).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetPredictionParameters returns the calculated diabetes parameters
 * @returns {$CancellablePromise<models$0.DiabetesParameters | null>}
 */
export function GetPredictionParameters() {
    return $Call.ByID(4062413646);
}

/**
 * GetPredictionWithScenario returns predictions with a hypothetical treatment
 * @param {number} additionalInsulin
 * @param {number} additionalCarbs
 * @returns {$CancellablePromise<models$0.PredictionResult | null>}
 */
export function GetPredictionWithScenario(additionalInsulin, additionalCarbs) {
    return $Call.ByID(3326799800, additionalInsulin, additionalCarbs).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * @returns {$CancellablePromise<models$0.Settings | null>}
 */
export function GetSettings() {
    return $Call.ByID(2612721090).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetTreatments returns recent treatments
 * @param {number} hours
 * @returns {$CancellablePromise<models$0.Treatment[]>}
 */
export function GetTreatments(hours) {
    return $Call.ByID(3347888222, hours).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType15($result);
    }));
}

/**
 * IsCalculating returns true if parameter calculation is in progress
 * @returns {$CancellablePromise<boolean>}
 */
export function IsCalculating() {
    return $Call.ByID(3719784624);
}

/**
 * @param {models$0.Settings | null} settings
 * @returns {$CancellablePromise<void>}
 */
export function SaveSettings(settings) {
    return $Call.ByID(1209878909, settings);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function SetApp(app) {
    return $Call.ByID(3576472702, app);
}

/**
 * @param {application$0.SystemTray | null} tray
 * @returns {$CancellablePromise<void>}
 */
export function SetTray(tray) {
    return $Call.ByID(2189598935, tray);
}

/**
 * StartParameterCalculation begins calculating diabetes parameters from historical data
 * @param {number} days
 * @returns {$CancellablePromise<void>}
 */
export function StartParameterCalculation(days) {
    return $Call.ByID(3846878363, days);
}

// Private type creation functions
const $$createType0 = models$0.CalculationProgress.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.ChartData.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = prediction$0.ChartPredictionData.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = models$0.GlucoseStatus.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.IOBCOBResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = models$0.PredictionResult.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = models$0.Settings.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = models$0.Treatment.createFrom;
const $$createType15 = $Create.Array($$createType14);
