// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as prediction$0 from "../prediction/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * CancelCalculation cancels an in-progress parameter calculation
 */
export function CancelCalculation(): $CancellablePromise<void> {
    return $Call.ByID(2320468136);
}

/**
 * GetCalculationProgress returns the progress of the current parameter calculation
 */
export function GetCalculationProgress(): $CancellablePromise<models$0.CalculationProgress | null> {
    return $Call.ByID(2929975047).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetChartData(hours: number, offsetHours: number): $CancellablePromise<models$0.ChartData | null> {
    return $Call.ByID(3917103465, hours, offsetHours).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetChartPredictionData returns prediction data formatted for the chart
 */
export function GetChartPredictionData(showLongTerm: boolean): $CancellablePromise<prediction$0.ChartPredictionData | null> {
    return $Call.ByID(3700879496, showLongTerm).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetCurrentStatus(): $CancellablePromise<models$0.GlucoseStatus | null> {
    return $Call.ByID(704641666).then(($result: any) => {
        return $$createType7($result);
    });
}

/**
 * GetIOBCOB returns current Insulin on Board and Carbs on Board
 */
export function GetIOBCOB(): $CancellablePromise<$models.IOBCOBResult | null> {
    return $Call.ByID(37726841).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * GetPrediction returns glucose predictions based on current data
 */
export function GetPrediction(): $CancellablePromise<models$0.PredictionResult | null> {
    return $Call.ByID(670056238).then(($result: any) => {
        return $$createType11($result);
    });
}

/**
 * GetPredictionParameters returns the calculated diabetes parameters
 */
export function GetPredictionParameters(): $CancellablePromise<models$0.DiabetesParameters | null> {
    return $Call.ByID(4062413646);
}

/**
 * GetPredictionWithScenario returns predictions with a hypothetical treatment
 */
export function GetPredictionWithScenario(additionalInsulin: number, additionalCarbs: number): $CancellablePromise<models$0.PredictionResult | null> {
    return $Call.ByID(3326799800, additionalInsulin, additionalCarbs).then(($result: any) => {
        return $$createType11($result);
    });
}

export function GetSettings(): $CancellablePromise<models$0.Settings | null> {
    return $Call.ByID(2612721090).then(($result: any) => {
        return $$createType13($result);
    });
}

/**
 * GetTreatments returns recent treatments
 */
export function GetTreatments(hours: number): $CancellablePromise<models$0.Treatment[]> {
    return $Call.ByID(3347888222, hours).then(($result: any) => {
        return $$createType15($result);
    });
}

/**
 * IsCalculating returns true if parameter calculation is in progress
 */
export function IsCalculating(): $CancellablePromise<boolean> {
    return $Call.ByID(3719784624);
}

export function SaveSettings(settings: models$0.Settings | null): $CancellablePromise<void> {
    return $Call.ByID(1209878909, settings);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3576472702, app);
}

export function SetTray(tray: application$0.SystemTray | null): $CancellablePromise<void> {
    return $Call.ByID(2189598935, tray);
}

/**
 * StartParameterCalculation begins calculating diabetes parameters from historical data
 * mode can be "statistical" or "ml"
 */
export function StartParameterCalculation(days: number, mode: string): $CancellablePromise<void> {
    return $Call.ByID(3846878363, days, mode);
}

// Private type creation functions
const $$createType0 = models$0.CalculationProgress.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.ChartData.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = prediction$0.ChartPredictionData.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = models$0.GlucoseStatus.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = $models.IOBCOBResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = models$0.PredictionResult.createFrom;
const $$createType11 = $Create.Nullable($$createType10);
const $$createType12 = models$0.Settings.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = models$0.Treatment.createFrom;
const $$createType15 = $Create.Array($$createType14);
