// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as models$0 from "../models/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../../wailsapp/wails/v3/pkg/application/models.js";

export function GetChartData(hours: number, offsetHours: number): $CancellablePromise<models$0.ChartData | null> {
    return $Call.ByID(3917103465, hours, offsetHours).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetCurrentStatus(): $CancellablePromise<models$0.GlucoseStatus | null> {
    return $Call.ByID(704641666).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetSettings(): $CancellablePromise<models$0.Settings | null> {
    return $Call.ByID(2612721090).then(($result: any) => {
        return $$createType5($result);
    });
}

export function SaveSettings(settings: models$0.Settings | null): $CancellablePromise<void> {
    return $Call.ByID(1209878909, settings);
}

export function SetApp(app: application$0.App | null): $CancellablePromise<void> {
    return $Call.ByID(3576472702, app);
}

export function SetTray(tray: application$0.SystemTray | null): $CancellablePromise<void> {
    return $Call.ByID(2189598935, tray);
}

// Private type creation functions
const $$createType0 = models$0.ChartData.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = models$0.GlucoseStatus.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = models$0.Settings.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
